# .github/workflows/deploy-example.yml

name: Deploy Example App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set VITE_BASE_PATH for Build
        run: |
          # 提取仓库名称
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          # 构造 base 路径，例如 /quick-cesium/
          VITE_BASE_PATH="/${REPO_NAME}/"
          echo "Calculated VITE_BASE_PATH: ${VITE_BASE_PATH}"
          # 将变量写入 GITHUB_ENV 文件，使其对后续步骤可用
          echo "VITE_BASE_PATH=${VITE_BASE_PATH}" >> $GITHUB_ENV

      - name: Build Example App
        run: pnpm run build --filter=@quick-cesium/example

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/example/dist
          publish_branch: gh-pages
